<?php

namespace Biblio\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArchivageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivageRepository extends EntityRepository
{
}
