biblio_pret_homepage:
    path:     /pret
    defaults: { _controller: BiblioPretBundle:Default:index }
biblio_pret_list:
    pattern:  /pret/list
    defaults: { _controller: BiblioPretBundle:Default:listPret }
biblio_pret_listByLivre:
    pattern:  /pret/list/livre
    defaults: { _controller: BiblioPretBundle:Default:listPretByLivre }
biblio_pret_listByEmprunteur:
    pattern:  /pret/list/emprunteur
    defaults: { _controller: BiblioPretBundle:Default:listPretByEmprunteur}
biblio_pret_livre:
    pattern:  /pret/dispo/
    defaults: { _controller: BiblioPretBundle:Default:isAvailable }
biblio_pret_hors_delai:
    pattern:  /pret/horsDelai
    defaults: { _controller: BiblioPretBundle:Default:listPretHorsDelai }
biblio_pret_sortie:
    path:     /pret/sortie
    defaults: { _controller: "BiblioPretBundle:Default:new" }
biblio_pret_sortie2:
    path:     /pret/sortie2
    defaults: { _controller: "BiblioPretBundle:Default:create" }
    requirements: { _method: post }
biblio_pret_retour:
    path:     /pret/{id}/delete
    defaults: { _controller: "BiblioPretBundle:Default:delete" }


