<?php

namespace Biblio\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LecteurRepository extends EntityRepository
{
	public function search($string)
	{
		$qb = $this->createQueryBuilder('l');
		$qb->where('l.nom LIKE :nom')
		->orWhere('l.prenom LIKE :nom')
     	->setParameter('nom','%'.$string.'%');
		 
		 return $qb->getQuery()->getResult();
	}
}
