<?php

namespace Biblio\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PretRepository extends EntityRepository
{
	public function findByLivre($titre) {
        $queryBuider = $this->createQueryBuilder('p');
        $queryBuider->leftJoin('p.livre', 'l')
                    ->where('l.titre = :titre')
                    ->setParameter('titre', $titre);
       return $queryBuider->getQuery()->getResult();
    }
    
   public function findByEmprunteur($nom,$prenom) {
        $queryBuider = $this->createQueryBuilder('p');
        $queryBuider->leftJoin('p.lecteur', 'l')
                    ->where('l.nom = :nom')
                    ->setParameter('nom', $nom)
                    ->andWhere('l.prenom = :prenom')
                    ->setParameter('prenom', $prenom);
       return $queryBuider->getQuery()->getResult();
    }
    
    public function findNbReservation($id) {
        $queryBuider = $this->createQueryBuilder('p');
        $queryBuider->select('COUNT(p)')
                    ->leftJoin('p.livre', 'l')
                    ->where('l.id = :id')
                    ->setParameter('id', $id)
                    ->andWhere('p.isReservation = 1');
       return $queryBuider->getQuery()->getSingleScalarResult();
    }
    
    public function findNbPret($id) {
        $queryBuider = $this->createQueryBuilder('p');
        $queryBuider->select('COUNT(p)')
                    ->leftJoin('p.lecteur', 'l')
                    ->where('l.id = :id')
                    ->setParameter('id', $id);
       return $queryBuider->getQuery()->getSingleScalarResult();
    }
    
    public function findPretHorsDelai() {
        $queryBuider = $this->createQueryBuilder('p');
        $queryBuider->leftJoin('p.lecteur', 'le')
                    ->leftJoin('le.cycle', 'c')
                    ->leftJoin('p.livre', 'li')
                    ->where("CURRENT_DATE() > DATE_ADD(p.dateReservation, c.dureePret, 'day')")
                    ->andWhere('c.id != 3');;
       return $queryBuider->getQuery()->getResult();
    }
   
    
    
}
