Biblio\EntityBundle\Entity\Archivage:
    type: entity
    table: null
    repositoryClass: Biblio\EntityBundle\Entity\ArchivageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomLivre:
            type: string
            length: '100'
        nomLecteur:
            type: string
            length: '50'
        prenomLecteur:
            type: string
            length: '50'
        dateEmprunt:
            type: date
        dateRetour:
            type: date              
lifecycleCallbacks: {  }