Biblio\EntityBundle\Entity\Lecteur:
    type: entity
    table: null
    repositoryClass: Biblio\EntityBundle\Entity\LecteurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: '50'
        prenom:
            type: string
            length: '50'                
    manyToOne:
        pret:
           targetEntity: Pret
           inversedBy: lecteurs
        cycle:
           targetEntity: Cycle
           inversedBy: lecteurs
        faculte:
           targetEntity: Faculte
           inversedBy: lecteurs
lifecycleCallbacks: {  }