pret:
    path:     /
    defaults: { _controller: "BiblioEntityBundle:Pret:index" }

pret_show:
    path:     /{id}/show
    defaults: { _controller: "BiblioEntityBundle:Pret:show" }

pret_new:
    path:     /new
    defaults: { _controller: "BiblioEntityBundle:Pret:new" }

pret_create:
    path:     /create
    defaults: { _controller: "BiblioEntityBundle:Pret:create" }
    requirements: { _method: post }

pret_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiblioEntityBundle:Pret:edit" }

pret_update:
    path:     /{id}/update
    defaults: { _controller: "BiblioEntityBundle:Pret:update" }
    requirements: { _method: post|put }

pret_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiblioEntityBundle:Pret:delete" }
    requirements: { _method: post|delete }
