biblio_entity_pret:
    resource: "@BiblioEntityBundle/Resources/config/routing/pret.yml"
    prefix:   /pret

biblio_entity_livre:
    resource: "@BiblioEntityBundle/Resources/config/routing/livre.yml"
    prefix:   /livre

biblio_entity_auteur:
    resource: "@BiblioEntityBundle/Resources/config/routing/auteur.yml"
    prefix:   /auteur

biblio_entity_homepage:
    path:     /hello/{name}
    defaults: { _controller: BiblioEntityBundle:Default:index }
