Biblio\EntityBundle\Entity\Lecteur:
    type: entity
    table: null
    repositoryClass: Biblio\EntityBundle\Entity\LecteurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '50'
        password:
            type: string
            length: '50'
        nom:
            type: string
            length: '50'
        prenom:
            type: string
            length: '50' 
    oneToMany:
        prets:
            targetEntity: Pret
            mappedBy: lecteur               
    manyToOne:
        cycle:
           targetEntity: Cycle
           inversedBy: lecteurs
        faculte:
           targetEntity: Faculte
           inversedBy: lecteurs
    manyToMany:
        roles:
            targetEntity: Role
            inversedBy: users

lifecycleCallbacks: {  }