Biblio\EntityBundle\Entity\Pret:
    type: entity
    table: null
    repositoryClass: Biblio\EntityBundle\Entity\PretRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateReservation:
            type: date
        isReservation:
            type: boolean                 
    manyToOne:
        livre:
           targetEntity: Livre
           inversedBy: prets
        lecteur:
           targetEntity: Lecteur
           inversedBy: prets
lifecycleCallbacks: {  }