biblio_inscription_lecteur_list:
    path:     administration/inscription/lecteur/list
    defaults: { _controller: BiblioInscriptionBundle:Lecteur:listAllLecteurs }

biblio_inscription_homepage:
    path:     administration/inscription/
    defaults: { _controller: "BiblioInscriptionBundle:Lecteur:index" }

biblio_inscription_show:
    path:     administration/inscription/lecteur/{id}/show
    defaults: { _controller: "BiblioInscriptionBundle:Lecteur:show" }

biblio_inscription_lecteur_new:
    path:     administration/inscription/lecteur/new
    defaults: { _controller: "BiblioInscriptionBundle:Lecteur:new" }

biblio_inscription_create:
    path:     administration/inscription/lecteur/create
    defaults: { _controller: "BiblioInscriptionBundle:Lecteur:create" }
    methods:  POST

biblio_inscription_edit:
    path:     administration/inscription/lecteur/{id}/edit
    defaults: { _controller: "BiblioInscriptionBundle:Lecteur:edit" }

biblio_inscription_update:
    path:     administration/inscription/lecteur/{id}/update
    defaults: { _controller: "BiblioInscriptionBundle:Lecteur:update" }
    methods:  [POST, PUT]

biblio_inscription_delete:
    path:     administration/inscription/lecteur/{id}/delete
    defaults: { _controller: "BiblioInscriptionBundle:Lecteur:delete" }
    methods:  [POST, DELETE]

